### ISSUE TITLE
Recommended testing instructions?

### ISSUE THREAD

**Issue by sorenbug** [SergiusTheBest/FindWDK#10]
https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-very-small-kmdf--driver#deploy-the-driver

![image](https://user-images.githubusercontent.com/7751296/77988372-0e305000-72d1-11ea-97ab-537be3b0f627.png)

No `inf` or `cat` is generated.

**Comment by SergiusTheBest** [comment]
Hi @sorenbug ,

`Inf` and `cat` parts are not implemented. For now you can use the following commandline tools: 

* `stampinf` to update `inf` files
* `inf2cat` to generate `cat`files

Note that `cat` files are no good for production as they are always regenerated by Microsoft driver signing portal.

I can't see anything CLion specific. If that's correct I'll change the issue description.

**Comment by sorenbug** [comment]
I figured it was CLion specific because VS automatically generates the inf and cat files. It's not.

**Comment by sorenbug** [comment]
As far as I can tell, `stampinf` has been what I want. When I get back to driver dev, I'll work on getting it integrated with CMake.
