### ISSUE TITLE
I have a qiestion,how to build  .asm file and Microsoft intrin.h func?

### ISSUE THREAD

**Issue by DiskGetor** [SergiusTheBest/FindWDK#11]

**Comment by DiskGetor** [comment]
Another problem is cmake can not build x64 win7 sys file,did you how to fix this?thank you

**Comment by SergiusTheBest** [comment]
Did you set WINVER?

**Comment by DiskGetor** [comment]
> 你设置WINVER了吗？

I was set winver to 0x0601,
Enablelanguage can find nasm,the the nasm was installed, cmd can find it.

**Comment by DiskGetor** [comment]
I using findwdk to build this project,the last problem is asm,link:
https://github.com/Gbps/gbhv

**Comment by SergiusTheBest** [comment]
@DiskGetor Did you manage to resolve the issue?

**Comment by DiskGetor** [comment]
> @DiskGetor您是否能够解决此问题？

I am trying to use zydis reapace lde64.lib now, the lib can not linked in clion with findwdk.

**Comment by DiskGetor** [comment]
> @DiskGetor Did you manage to resolve the issue?

hello again.
target_link_libraries(hvm  WDK::NTSTRSAFE)
do not work,can you help me? thank you. test code:

#include <ntstrsafe.h>
   char src[777] = "i am src";
    char dst[777] = {0};
    RtlStringCbPrintfA(dst, BUFSIZ, "%s", src);
    DbgPrint(dst);

**Comment by SergiusTheBest** [comment]
@DiskGetor Ok, this one is fixed. Please, create a new issue for a new question - it will be easier to track them.

**Comment by DiskGetor** [comment]
> @DiskGetor好的，这个是固定的。请为一个新问题创建一个新问题-追踪它们会更容易。

You are very very cool,thank you again.
