### ISSUE TITLE
DriverEntry not working on windows7 X64

### ISSUE THREAD

**Issue by DiskGetor** [SergiusTheBest/FindWDK#13]
hello again, if set this:

```
string(CONCAT WDK_LINK_FLAGS
#        "/ENTRY:DriverEntry "  
```

why this do not work,if modifly DriverEntry to FxDriverEntry,sys load ok,but build err so.

then i creat vsproject use cmakeGUI, i found the complie is FxDriverEntry, and i delete Fx, the sys file was loaded on win7. so my problen is how to set:  "/ENTRY:DriverEntry "  ? thx.

**Comment by DiskGetor** [comment]
> 你为什么要改变它？

Because if do not change to drivrentry the sys can't load.

**Comment by SergiusTheBest** [comment]
I checked and it was loaded with no issues. Could you post your cmake code here?

**Comment by DiskGetor** [comment]
You are right
