### ISSUE TITLE
ZERO_CHECK error when WindowsKernelModeDriver10.0 is selected as platform toolset

### ISSUE THREAD

**Issue by venkateshmicro98** [SergiusTheBest/FindWDK#22]
When I select "WindowsKernelModeDriver10.0" as platform toolset like this 
<img width="563" alt="image" src="https://user-images.githubusercontent.com/31404179/128122089-88779c7e-c1c2-479c-a7d0-cafb47fa4a2c.png">
I am getting an error in zero check
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/31404179/128122135-7034768d-d477-402a-bb61-01d4ccfcb57d.png">

WDK version : 10

**Comment by SergiusTheBest** [comment]
You shouldn't make any changes to project properties - they will be lost and rewritten by CMake (of cause if ZERO_CHECK will run successfully). In your case recreate project files with CMake command line or GUI application.

**Comment by venkateshmicro98** [comment]
Got it
