### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by venkateshmicro98** [SergiusTheBest/FindWDK#23]
https://github.com/SergiusTheBest/FindWDK/blob/0c276ffcd706ec04df13e8a97d42afc020003e73/cmake/FindWdk.cmake#L167

${WDK_COMPILE_DEFINITIONS};$<$<CONFIG:Debug>:${WDK_COMPILE_DEFINITIONS_DEBUG}
**>**
;_WIN32_WINNT=${WDK_WINVER}

Is this intended or Typo?

**Comment by SergiusTheBest** [comment]
Looks like a typo. Let me check it.

**Comment by SergiusTheBest** [comment]
Thanks!
