### ISSUE TITLE
about Wpp Tracing

### ISSUE THREAD

**Issue by durongze** [SergiusTheBest/FindWDK#30]
![image](https://github.com/SergiusTheBest/FindWDK/assets/4144559/7e5276f3-98ea-4fba-b354-c598181b8558)
Why is there no wpp option？
----------------------------------------------------

**In general, kmdf has a wpp option, for example:**
![Y_MQ$R2CSB@ NUQV 4~C}D](https://github.com/SergiusTheBest/FindWDK/assets/4144559/0e9a8b30-6398-4b7b-a35b-b3e336d62883)

**Comment by SergiusTheBest** [comment]
There was no need to support WPP thus it's left unimplemented :disappointed:

**Comment by durongze** [comment]
感谢回复。
