### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by nblog** [SergiusTheBest/FindWDK#31]
Are there any plans to support [ARM64](https://learn.microsoft.com/windows-hardware/drivers/develop/building-arm64-drivers) ?

**Comment by SergiusTheBest** [comment]
Yes. Do you have ARM hardware to help with testing?

**Comment by nblog** [comment]
> Yes. Do you have ARM hardware to help with testing?

Yes, when the project supports ARM64 (CPU: Snapdragon X Elite), I'm more than happy to test it.

**Comment by SergiusTheBest** [comment]
Excellent!

**Comment by SergiusTheBest** [comment]
@nblog Please, test the `arm64-support` branch.

**Comment by nblog** [comment]
How do I sign the driver (Test Sign)? Although I have test mode turned on, it doesn't seem to allow loading of unsigned drivers ! ([SC] StartService Failed 577)

But the driver I used Sign Mode (Test Sign) loads properly in Test Mode.

**Comment by nblog** [comment]
**Test Environment: Windows 10 22H2 10.0.19045.2486 (Arm64)**

[KmdfCppDriver](https://github.com/SergiusTheBest/FindWDK/tree/master/samples/KmdfCppDriver):
Build: ok
Output: no output **The answer is ${answer}**

[MinifilterCppDriver](https://github.com/SergiusTheBest/FindWDK/tree/master/samples/MinifilterCppDriver):
Build: ok
Output: **FltRegisterFilter** (C0000034)

[WdmCppDriver](https://github.com/SergiusTheBest/FindWDK/tree/master/samples/WdmCppDriver):
Build: ok
Output: ok

[WdmDriver](https://github.com/SergiusTheBest/FindWDK/tree/master/samples/WdmDriver):
Build: ok
Output: ok

**Comment by nblog** [comment]
Test Environment: Windows 11 23H2 10.0.22631.2428 (Arm64)

KmdfCppDriver
Build: ok
Output: ok

MinifilterCppDriver
Build: ok
Output: FltRegisterFilter (0xC01C0011 as always)

WdmCppDriver
Build: ok
Output: ok

WdmDriver
Build: ok
Output: ok



@SergiusTheBest 
I think [#32](https://github.com/SergiusTheBest/FindWDK/pull/32) is ready and ended up just adding two definitions to the base “_USE_DECLSPECS_FOR_SAL=1;STD_CALL” to keep it the same as VS2022

**Comment by SergiusTheBest** [comment]
#32 is merged! Thank you!
