### ISSUE TITLE
How to sign the driver?

### ISSUE THREAD

**Issue by dmikushin** [SergiusTheBest/FindWDK#7]
How does one sign the driver generated by `wdk_add_driver` ?

**Comment by SergiusTheBest** [comment]
You can sign a driver with `signtool` (using `add_custom_command` in cmake). 

Note that Windows 10 requires a complex signing procedure with hardware token, cab archives and uploading/downloading from the Microsoft web site.

**Comment by dmikushin** [comment]
I'm trying to automate signing process for modern re-incarnation of
USBSnoop tool: https://github.com/dmikushin/usbsnoop
My current CMake rules are signing .sys files directly, which apparently
does not work. I'd really appreciate a detailed example on how to manage
this with .cab, if you know any.
Anyway, many thanks for the pointer!

чт, 13 сент. 2018 г. в 12:28, Sergey Podobry <notifications@github.com>:

**Comment by SergiusTheBest** [comment]
Oh, I used USBSnoop in the past! For signing procedure you can refer to this MSDN guide: https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/attestation-signing-a-kernel-driver-for-public-release

**Comment by SergiusTheBest** [comment]
Also you need to buy a EV certificate. The best price I know is [here](https://www.digicert.com/friends/sysdev/).

**Comment by dmikushin** [comment]
Thanks, @SergiusTheBest !

I've ended up with a soft compromise: self-signed drivers. Poorman solution, which works given that the "test signing" is enabled in the target system.

One who would come across this question may find useful how CMake-based signing is made on top of FindWDK here: https://github.com/SnoopWare/usbsnoop/blob/master/CMakeLists.txt

FWIW here is the first modern USBSnoop release, which is also based on your work: https://github.com/SnoopWare/usbsnoop/releases/tag/0.26g.2
